/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as WatchlistIndexImport } from './routes/watchlist/index'
import { Route as DiscoverIndexImport } from './routes/discover/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WatchlistIndexRoute = WatchlistIndexImport.update({
  path: '/watchlist/',
  getParentRoute: () => rootRoute,
} as any)

const DiscoverIndexRoute = DiscoverIndexImport.update({
  path: '/discover/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/discover/': {
      id: '/discover/'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverIndexImport
      parentRoute: typeof rootRoute
    }
    '/watchlist/': {
      id: '/watchlist/'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  DiscoverIndexRoute,
  WatchlistIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/discover/",
        "/watchlist/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/discover/": {
      "filePath": "discover/index.tsx"
    },
    "/watchlist/": {
      "filePath": "watchlist/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
